/// <auto-generated> 
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace RgAbilitybotCs
{
    public class SelectARandomEntity : ConditionNode
    {
        public SelectARandomEntity() : base("Select a random entity")
        {
        }

        /**
         * Generated from prompt:
         * 
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var random = new System.Random();
        	var entities = rgObject.FindEntities();
        	if (entities.Count > 0)
        	{
        		var selectedIndex = random.Next(entities.Count);
        		var target = entities[selectedIndex];
        		SetData("targetEntity", target);
        		return NodeStatus.Success;
        	}
        
        	return NodeStatus.Failure;
        }
    }
}